// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkqdkjvdpkcxifzutocu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrcWRranZkcGtjeGlmenV0b2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTc5MTEsImV4cCI6MjA2MTEzMzkxMX0.L2D530Vkbx38SPJmBA-t-1VFtJ2RTLzzylCZ3go3yOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);